spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dshilja/CC-projekt/tree/main/config
        native:
          search-locations: classpath:.
  profiles:
    active: native
